version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: carapp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: carapp_db
      MYSQL_USER: caruser
      MYSQL_PASSWORD: Admin123
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
